# Generated by Django 5.1.15 on 2026-04-02 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_treenode_usertreestate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertreestate',
            name='workspace_id',
        ),
        migrations.AddField(
            model_name='usertreestate',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.workspace'),
        ),
    ]
