# Generated by Django 6.0.4 on 2026-04-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_pastedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastedfile',
            name='md5_hash',
            field=models.CharField(db_index=True, default='', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
