# Generated by Django 5.2.13 on 2026-04-30 08:38

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
import hashlib

def generate_md5(apps, schema_editor):
    UploadedFile = apps.get_model('notes', 'UploadedFile')

    for obj in UploadedFile.objects.all():
        if obj.file:
            try:
                with obj.file.open('rb') as f:
                    obj.md5_hash = hashlib.md5(f.read()).hexdigest()
                obj.save()
            except Exception:
                obj.md5_hash = None
                obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_pastedfile_md5_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='user',
            field=models.ForeignKey(
                null=True,  
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),

            preserve_default=False,
            # migrations.RunPython(generate_md5),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='md5_hash',
            field=models.CharField(max_length=32, null=True),
            # preserve_default=False,
        ),
        migrations.RunPython(generate_md5),
    ]

   