# Generated by Django 6.0.5 on 2026-05-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_alter_uploadedfile_md5_hash_workspacemembership_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTreeState',
        ),
    ]
