# Generated by Django 6.0.5 on 2026-06-02 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_delete_usertreestate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='workspace',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='page',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('workspace', 'slug'), name='notes_page_workspace_slug_active'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('owner', 'slug'), name='notes_workspace_owner_slug_active'),
        ),
    ]
