# Generated by Django 6.0.5 on 2026-06-10 17:35

import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_remove_page_alternate_editors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceinvite',
            name='token',
            field=models.CharField(default=notes.models._invite_token, max_length=64, unique=True),
        ),
    ]
