# Generated by Django 5.1.15 on 2026-06-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_alter_workspaceinvite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='left_panel_expanded',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='right_panel_expanded',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='sidebar_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
