# Generated by Django 5.1.15 on 2026-06-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_user_settings_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='right_panel_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
