# Generated by Django 5.1.15 on 2026-06-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0023_encrypt_db_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dmpeersignal',
            new_name='notes_dmpee_recipie_f177b0_idx',
            old_name='notes_dmpeer_recip_id_idx',
        ),
    ]
