# Generated by Django 5.1.15 on 2026-06-17 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0024_rename_notes_dmpeer_recip_id_idx_notes_dmpee_recipie_f177b0_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='notes.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_tags', to='notes.page')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_tags', to='notes.tag')),
            ],
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['workspace', 'name'], name='notes_tag_workspa_699260_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='notes_tag_workspace_name'),
        ),
        migrations.AddConstraint(
            model_name='pagetag',
            constraint=models.UniqueConstraint(fields=('page', 'tag'), name='notes_pagetag_page_tag'),
        ),
    ]
