# Generated by Django 5.1.15 on 2026-07-05 17:08

import django.db.models.deletion
import notes.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0029_incoming_mail_eml'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', notes.fields.EncryptedTextField(blank=True, default='')),
                ('body', notes.fields.EncryptedTextField(blank=True, default='')),
                ('color', models.CharField(choices=[('default', 'Default'), ('coral', 'Coral'), ('peach', 'Peach'), ('sand', 'Sand'), ('mint', 'Mint'), ('sage', 'Sage'), ('fog', 'Fog'), ('storm', 'Storm'), ('dark', 'Dark')], default='default', max_length=16)),
                ('pinned', models.BooleanField(default=False)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_notes', to='notes.workspace')),
            ],
            options={
                'ordering': ['-pinned', '-updated_at', '-id'],
            },
        ),
    ]
